version: '3'

services:
  jenkins:
    build: .
    ports:
    - 9000:8080
    - 50000:50000
  gogs:
    image: gogs/gogs:latest
    ports:
    - 9001:3000
  registry:
    image: registry:2
    ports:
    - 9002:5000
